### ISSUE TITLE
Expired queue remain in the waiting room size

### ISSUE THREAD

**Issue by cccdi** [aws-solutions/virtual-waiting-room-on-aws#208]
**Describe the bug**
expired queue should not be count under waiting room size as they are not waiting and expired.

**To Reproduce** 
1. Create 6 user
2. add 4 serving count
3. user 1 & 2 enter website
4. user 3 & 4 wait until queue expiry
5. user 5 & 6 can now enter the website
6. but the Waiting Room Size keep showing 2 which the queue should be 0 now

**Expected behavior**
Expected Waiting Room Size update to 0

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

<img width="1308" alt="Screenshot 2022-09-15 at 6 36 00 PM" src="https://user-images.githubusercontent.com/33714172/190383058-4dc2f2d3-9d51-4dd8-88ea-da5b31c5efbf.png">

**Additional context**
Version: [v1.1.0]

**Comment by cassneal** [comment]
Thanks for reporting this. We have added it to our backlog to look into.

**Comment by bassemwanis** [comment]
Hi @cccdi,

The fix for this issue has been included in release 1.1.3. Please feel free to verify the fix, and don't hesitate to reach out if you encounter any further issues.

Thank you!
