### ISSUE TITLE
queue_num api return same result after reset

### ISSUE THREAD

**Issue by cccdi** [aws-solutions/virtual-waiting-room-on-aws#214]
**Describe the bug**
queue_num api return same result after reset

**To Reproduce**
after reset , used old api request id to call queue_num api can return old queue number.

**Expected behavior**
error message from api

**Please complete the following information about the solution:**
- Version: [e.g. v1.1.0]

**Comment by cassneal** [comment]
Thanks for reporting this. We have added it to our backlog to look into.

**Comment by thyagram-aws** [comment]
The reset process can take a few minutes to completely take effect. You could check your Cloud Watch logs to make sure the reset is completed and successful. One of the indicators of a successful reset is that the QueuePositionEntryTime DynamoDB table should be empty. 
Could you verify if the above criteria are met before re-invoking the queue_num API?

**Comment by cccdi** [comment]
@thyagram-aws Please see screen cap below. double checked return same result after mins. And the reason that I found out is : by lambda test trigger I can return expected error "Request ID not found" . Therefore the issue should caused by Cloudfront, I can see respond header "X-Cache: Hit from Cloudfront" as this is a get request so the result should be cached by Cloudfront even lambda already return "Request ID not found".


<img width="604" alt="Screenshot 2022-09-23 at 10 41 29 AM" src="https://user-images.githubusercontent.com/33714172/191883768-c96ff862-9166-4829-a965-53f01b90a38a.png">
<img width="809" alt="Screenshot 2022-09-23 at 10 41 55 AM" src="https://user-images.githubusercontent.com/33714172/191883772-469ddf49-9dae-4e34-972d-0913d2c2a79d.png">

**Comment by gsingh04** [comment]
Hello @cccdi, apologies for delay in response from our end.
We were able to replicate the issue, which is due to the request hitting cloudfront cache as you highlighted. We are working on the fix and it will be addressed in next release.

**Comment by bassemwanis** [comment]
The fix for this issue has been included in release 1.1.3.
