### ISSUE TITLE
Token Expiry & Serving Counter Enhancement 

### ISSUE THREAD

**Issue by tunlinphyo** [aws-solutions/virtual-waiting-room-on-aws#265]
**Request**
I'm seeking a method to invalidate a token before its designated expiration time.

**My Store Features**
- Customers receive a token for a single checkout session.
- After checkout, the token is cleared for the customer, requiring them to request a new queue number.
- I aim to boost the serving counter based on the number of "Active Tokens". For instance, if the count of "Active Tokens" falls below 50, I want to automatically increase the serving count by 50.

**Problem**
Even after a token is cleared from a user, the VWR system continues to mark it as active due to the fixed expiration time.

**Comment by bassemwanis** [comment]
Thank you @tunlinphyo for requesting this enhancement. Regarding your suggestion to invalidate a token before its designated expiration time, you can achieve that by using the `/update_session` private endpoint after the checkout logic. Session status is denoted by an integer (0 indicates `active`, 1 indicates `completed`, and -1 indicates `abandoned`). For more details on `/update_session` private API, refer to our developer guide [here](https://github.com/aws-solutions/virtual-waiting-room-on-aws/blob/main/docs/developer-guide.md#private-rest-apis).

**Comment by tunlinphyo** [comment]
Thank you, @bassemwanis, for your kind response. I apologize for my lack of knowledge.
