### ISSUE TITLE
Unable to Launch "Core Module Stack" CloudFormation  

### ISSUE THREAD

**Issue by shaheerkhan12605** [aws-solutions/virtual-waiting-room-on-aws#275]
**Describe the bug**

Unable to provision Code Module Stack in CloudFormation template, The `PublicWaitingRoomApiDeployment` is not being created caused the Failure

**To Reproduce**

- Launch Core Module Stack Individually from the following Link 

https://docs.aws.amazon.com/solutions/latest/virtual-waiting-room-on-aws/deploying-separate-stacks.html#launch-the-core-stack

**OR**
- Launch Automated Deployment from the following Link

https://docs.aws.amazon.com/solutions/latest/virtual-waiting-room-on-aws/automated-deployment.html#step-1.-launch-the-getting-started-stack

**Expected behavior**

Core Module Stack should be created without any errors

**Please complete the following information about the solution:**
- [ ] Version: v1.1.8

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? **No**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/02c7e37a-1d33-42d4-91be-7323f208af0a">

**Additional context**
N/A

**Comment by bassemwanis** [comment]
Hi @shaheerkhan12605, thank you for reaching out. It’s likely you haven't completed these prerequisite steps to activate CloudWatch logging from API Gateway: https://docs.aws.amazon.com/solutions/latest/virtual-waiting-room-on-aws/automated-deployment.html#prerequisites.
Mainly you need to install the [virtual-waiting-room-on-aws-api-gateway-cw-logs-role.template](https://solutions-reference.s3.amazonaws.com/virtual-waiting-room-on-aws/latest/virtual-waiting-room-on-aws-api-gateway-cw-logs-role.template)

**Comment by shaheerkhan12605** [comment]
Thanks for the update. Closing the issue.
